<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class GalleryScrapperSettings
{
    private $gallery_scrapper_settings_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'gallery_scrapper_settings_add_plugin_page'));
        add_action('admin_init', array($this, 'gallery_scrapper_settings_page_init'));
    }

    public function gallery_scrapper_settings_add_plugin_page()
    {
        add_menu_page(
            'Gallery Scrapper Settings', // page_title
            'Gallery Scrapper Settings', // menu_title
            'manage_options', // capability
            'gallery-scrapper-settings', // menu_slug
            array($this, 'gallery_scrapper_settings_create_admin_page'), // function
            'dashicons-format-gallery', // icon_url
            65 // position
        );
    }

    public function gallery_scrapper_settings_create_admin_page()
    {
        $this->gallery_scrapper_settings_options = get_option('gallery_scrapper_settings_option_name'); ?>

        <div class="wrap">
            <h2>Gallery Scrapper Settings</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('gallery_scrapper_settings_option_group');
                do_settings_sections('gallery-scrapper-settings-admin');
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function gallery_scrapper_settings_page_init()
    {
        register_setting(
            'gallery_scrapper_settings_option_group', // option_group
            'gallery_scrapper_settings_option_name', // option_name
            array($this, 'gallery_scrapper_settings_sanitize') // sanitize_callback
        );

        add_settings_section(
            'gallery_scrapper_settings_setting_section', // id
            'Settings', // title
            array($this, 'gallery_scrapper_settings_section_info'), // callback
            'gallery-scrapper-settings-admin' // page
        );

        add_settings_field(
            'ttest_0', // id
            'TTEST', // title
            array($this, 'ttest_0_callback'), // callback
            'gallery-scrapper-settings-admin', // page
            'gallery_scrapper_settings_setting_section' // section
        );
    }

    public function gallery_scrapper_settings_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['ttest_0'])) {
            $sanitary_values['ttest_0'] = sanitize_text_field($input['ttest_0']);
        }

        return $sanitary_values;
    }

    public function gallery_scrapper_settings_section_info()
    {

    }

    public function ttest_0_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="gallery_scrapper_settings_option_name[ttest_0]" id="ttest_0" value="%s">',
            isset($this->gallery_scrapper_settings_options['ttest_0']) ? esc_attr($this->gallery_scrapper_settings_options['ttest_0']) : ''
        );
    }

}

if (is_admin())
    $gallery_scrapper_settings = new GalleryScrapperSettings();

/* 
 * Retrieve this value with:
 * $gallery_scrapper_settings_options = get_option( 'gallery_scrapper_settings_option_name' ); // Array of All Options
 * $ttest_0 = $gallery_scrapper_settings_options['ttest_0']; // TTEST
 */
